version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  commands:
    - echo "Node js is installing"
    - npm ci --legacy-peer-deeps

build:
  commands:
    - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: build
  discard-paths: no
